### ISSUE TITLE
Revise background smartctl calling

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#70]
The current implementation of emhttp does polling and storing of the smart attrbiutes of the disks at regular intervals in the background, by calling smartctl -A.

This approach has a performance impact when doing parity operations (and possibly when accessing files during normal operation).

Some ideas:
- Lower the poll frequency (e.g. every X minutes, though this requires adjustment to notifications too)
- A more distributed way of calling the individual disks.
- A back-off mechanism when a parity operation is in progress
- A back-off mechanism for active drives (read/write in progress)

**Comment by limetech** [comment]
The 'poll_spindown' sys config variable has been renamed 'poll_attributes' and specifies the time in seconds between invoking 'smartctl -A' on each of the assigned devices.  The default has been set to 1800 (30 min).  The first poll will take place immediately following an array start.

I got 30 min from the default setting for 'smartd --interval'.  I guess we could just use smartd but there are some things we can do in a future release to be a little more intelligent about how often SMART data is read.  For example, we can auto-adjust the polling frequency per device based on how often the data is changing.  Let's say we poll a HDD temperature and read 35C.  30 minute later it still reads 35C, so we might extend this device polling to 45 minutes.  On the other hand, say we find the temperature has raised to 38C, so we might decrease the polling to 20 min.

Another idea as you mention above would be to implement polling back-off mechanisms based on the type of I/O we're seeing to the devices.  These kinds of specialized SMART data gathering can't be done using smartd AFAIK.

For now, simply raising the polling freq to 30 min will go a long way to minimize impact on parity operations.

How are notifications affected by this?

**Comment by bergware** [comment]
I was reading too about smartd, and see its default interval is 30 minutes, which can be adjusted.

The monitor script which is run every minute uses the smart output file under "/var/local/emhttp/smart" to report about temperatures, attributes threshold exceedings and number of active devices. By lowering the update frequency to 30 minutes, it isn't really giving up-to-date information anymore to the monitor script.

Perhaps some alignment in timers for both the monitor script and the smart reports ?

**Comment by limetech** [comment]
Here is the reality to deal with.  Reading HDD SMART attributes is a very "expensive" operation in terms of its affect on I/O throughput.  First, the linux device drivers "plug" the I/O queue for the device, send the SMART command down, wait for SMART command completion, then unplug the I/O queue.  Second, the device itself executes a long seek to the inner cylinder (typically) where it stores the SMART data.  When I/O resumes, the heads will again seek back to where they were.  Third, if the HDD is spun down, the device will spin up.

Because of this you can't just poll SMART data every second, or (turns out) every 10 sec without causing significant I/O performance issues.

Prior to dynamix, unRaid would read SMART data only "on demand" via weGui - meaning as a result of a user click (this was one reason for "slowness" in webGui response).  In addition, we always use the "-n standby" option to leave sleeping disks alone (still do).  If as a result of clicking 'refresh' in the webGui a user would notice glitch in media playback I would say, "Don't refresh webGui during media playback."

I hope this clears things up a bit.  I think it's fine that certain information is not "real time", certainly for 6.0-final release.  Even with poll_attributes set at 30 min I bet eventually we might see a forum post from someone complaining they seem to see a video glitch every 30 min.

Another idea I've had to address such "glitching" is to create a share attribute called "optimize for streaming".  What this would do is implement a more aggressive internal read-ahead.  One would set this on their 'Movies' share for example.
