### ISSUE TITLE
Move "Mover Settings" to "Scheduler" page

### ISSUE THREAD

**Issue by jonpanozzo** [limetech/dynamix#74]
Tom and I had discussed this a while back and I think it's coming to the time for us to do this.  Essentially what needs to happen is the mover settings at present are located on the Global Share Settings page.  This needs to be relocated to the Scheduler page as it makes much more sense to keep all scheduled events (such as the mover) grouped together.

**Comment by bergware** [comment]
Agree that the current position of Mover is too hidden for most people and the more logical place is under Scheduler.

**Comment by limetech** [comment]
This is not a huge priority, but also not hard to do either, I guess I don't care if it gets in now or later.

But if you want a nice little problem to solve, how about this:  When you download a container in docker manager a windows opens that shows progress.  We need to do this for the plugin manager.  This is because when someone upgrades to new release of unRaid the download is 90MB+ and it looks like it is just "hanging".  I used to have a simple thing that used 'pv' to display progress but that got removed somewhere along the way

What I had in mind was something like what's described here:
http://fitnr.com/showing-file-download-progress-using-wget.html

In our case we could use php popen() to execute the 'plugin install' command, and then read the lines one-by-one and selectively send them to the browser using "log_Prog()" function found in docker manager.

Anyway this would be a nice little puzzle to solve.

**Comment by bergware** [comment]
Moving the Mover I have done already, will upload to github later (indeed a 5 minutes job).

I'll think about the progress indicator, and see if I can come up with something 'nice' ...

**Comment by limetech** [comment]
Have you had a chance to download -beta14b?  Actually I have a -beta14c that further refines how temperatures are read....

But I wanted to point out that I 'commented out' the pluginURL entity in the dynamix.plg file.  This is because every time I post a new unRaid release it's inevitable that dynamix version updates as well.  This causes both 'dynamix' and 'unRAIDServer' to show "update available" on plugin page; but, we don't want user to update dynamix because he'll get it included when he updates unRaid release.  By omitting the pluginURL it prohibits separate download of dynamix (at least the version hosted here on limetech github).

**Comment by bergware** [comment]
No, I am still on 14a. Should I wait until 14c is available ?

**Comment by limetech** [comment]
14b solves some regressions introduced in 14a :/  So I recommend updating.  After updating you'll see some strange things with spinning status and temperatures, eg, drive spun down but still shows valid temperature.  This is because smart polling is independent of spinning state check.  14c solves most of these anomalies.  Besides... you can test your new plugin download progress thingy :)

**Comment by limetech** [comment]
Also, a new disk var was added called 'rotational'.  This is set to either <blank> if no device, or to "0" meaning SSD device or to "1" meaning HDD device.  Already it fixes issue where, after eg, spindown of all disks, an SSD device would show as spun down when really its not.  What I didn't fix was the rollover on the colored orbs on the Main page - no need to offer a spin-down for an SSD.

**Comment by jonpanozzo** [comment]
Ronald,

Great work on moving the mover settings.  One last tweak to this.  You currently display a "Status:  Running" in the top right.  now that we've turned the "Scheduler" page into a repo for other schedulable tasks, the top bar is listed as "Parity Check," so by having it show "Status:  Running" would confuse someone to think that meant a parity check is running.

Solution?  Remove that status from being displayed altogether.  I think that if the drop down is set to "Disabled" or "Enabled", that pretty much covers it right there.  Anyway, just my 2 cents,

**Comment by bergware** [comment]
The "trick" I introduced is that "Parity-check" is the first tab and it shows a status. Clicking on the next tab (Mover in this case) will hide the status message, while moving back to the first tab shows the status again.

I hope that makes it clear the status belongs to "parity-check". Otherwise we need to rethink the placement of the status ...

**Comment by limetech** [comment]
I got the progress working correctly... will push out with next release.

**Comment by bergware** [comment]
Excellent .. was twisting my head around that, good to have it working !

**Comment by jonpanozzo** [comment]
Well the problem is that status is really referring to the fact that the scheduler is enabled, not that an actual parity check is running right then and there, correct?  That’s what I think will confuse people.






Sent from Windows Mail





From: bergware
Sent: ‎Thursday‎, ‎February‎ ‎26‎, ‎2015 ‎1‎:‎40‎ ‎PM
To: limetech/dynamix
Cc: jonp@lime-technology.com





The "trick" I introduced is that "Parity-check" is the first tab and it shows a status. Clicking on the next tab (Mover in this case) will hide the status message, while moving back to the first tab shows the status again.

I hope that makes it clear the status belongs to "parity-check". Otherwise we need to rethink the placement of the status ...

**Comment by bergware** [comment]
I see the confusion ...

The status refers to the scheduler running not the actual parity-check itself.

This has a bit of historical reason, in the past it could happen that the scheduler process wasn't started properly and in this situation it gave the user the false notion that a parity check would be executed at the given time and date.

The status message gives the feedback that the scheduler indeed is active.

In the new approach this is less likely to happen though.

**Comment by bergware** [comment]
I removed the status message from parity-check, less confusing. Will post an update later.

**Comment by jonpanozzo** [comment]
Now you get what I’m talking about.  I think the “enabled / disabled” drop down is their indication if the setting is set properly.  If someone doesn’t see the parity check running when it’s supposed to, we’ll need to get a syslog and troubleshoot.  I really see no need to display a status in the top right as it will definitely generate confusion and make people think that a parity check itself is “running.”  Existing users of the notifications system will understand what it means, but when we go final, a bunch of 5.x users will guaranteed to be thrown off.
