### ISSUE TITLE
Notifications challenges

### ISSUE THREAD

**Issue by bergware** [limetech/dynamix#81]
Based on feedback from the forum I did some further investigation in the notifications system not working properly after a reboot. There are two conditions which prevent notifications to start working:

1. The archive folder by default is set to /tmp/notifications which is not created after a reboot. This is only done when the webGui is opened and issues a "notify init" command.

2. The monitor script reads the files disks.ini and var.ini, these files however do not exist until the webGui is opened a first time and emhttp kicks in.

There might also be a race condition when the archive folder is moved to a disk or share, it might be that the disk or share is not available yet or not available anymore.

Currently rc.local does a "notify smtp-init", it can do a "notify init" as well, this would overcome point 1, but maybe there are better solutions ?

Not sure how to tackle point 2, or is there a way to force the creation of all the .ini files ?

The race condition may or may not be an issue (I suppose when it happens it simply does not store the notifications and they are lost).

Thoughts ?

**Comment by limetech** [comment]
Actually #2 is easier to solve.  At the top before any status is queried there should be a line like this:
```
exec("/usr/bin/wget -q -O - localhost/update.htm?cmdStatus=apply");
```
Could use wget or curl.  The idea is that this causes emhttp to execute an internal 'refresh status' operation which results in all those ini files getting regenerated.

The fact that monitor script does not have this should be considered a bug because other than webGui access, there is nothing else that refreshes the ini files.

Issue #1 is tricky because of aforementioned race conditions.  I will change rc.local to include a call to 'notify init' just before call to 'notifiy smtp-init'.  But if user has specified a disk or a share to store notifications this will be a problem.

Curious: why do we need to let user configure this?  Why not just always use /tmp/notifications dir?

**Comment by bergware** [comment]
The intention of the path configuration is/was to give the user the oppertunity to save the notifications in non-volatile memory - if desired.

Perhaps to avoid all these "difficulties" we can simply remove the selection and have the path fixed to "/tmp/notifications" or some other suitable location, it may also simplify the one time creation of this location.

**Comment by limetech** [comment]
They could be saved on the flash in /boot/config/notifications
Maybe instead of letting user configure a path, we give them a checkbox that says something like "Save notifications".  If 'Yes' then we set path on the flash, if 'No' then we set path on /tmp.  If someone is configured to email notifications they would probably have setting to 'No'.
This way no matter which they choose 'rc.notify init' will not fail if it needs to create the directories.

**Comment by bergware** [comment]
yeah, that is an option. What about flash wear-and-tear, it is afterall more writing to the flash, which personally I like to minimize as much as possible, but maybe I am just too concerned here !

**Comment by limetech** [comment]
That's a reason to provide a Yes/No selection.  I think the flash wear and tear is waaay overstated.  I have flash devices which have been used for several years in test servers where new OS releases are routinely written to them (90MB+ each).  Never any problems.  Consider your cell phone: those things have flash devices too, yet no one really complains much about their memory failing.  Sure it can happen, but I think it's really rare, especially if you have quality name-brand device.

**Comment by bergware** [comment]
My first USB stick is 5 years old (build unRAID system in 2010) and still going strong :)

I replace the path field with a selection box:
Store notifications to flash: no/yes

**Comment by limetech** [comment]
Yes that sounds good ;)

**Comment by bergware** [comment]
Doing the wget command every minute (this is the frequency of the monitor script), will this initiate every minute a smartctl command for all disks and possible impact on read/write performance ?

Or runs smartctl now completely independent and its frequency is solely determined by the new parameter 'poll-attributes' ?

**Comment by bergware** [comment]
I included the creation of the directories under "smtp-init", there is no need to adjust rc.local.

**Comment by limetech** [comment]
> Doing the wget command every minute (this is the frequency of the monitor script), will this initiate every minute a smartctl command for all disks and possible impact on read/write performance ?

emhttp includes a thread which wakes up every second to check for drives to spin down, based solely on I/O activity.  It also checks for time to read temperatures after 'poll_attributes' seconds.  It immediately reads smart data for cmdSpinup or cmdSpinupAll.  (The temperature setting for a device is set to '*' as are result of cmdSpindown or cmdSpindownall.)  Something I've been meaning to add is a "poll_spindown" event which would occur every second at end of polling loop.  We could use this, e.g., to execute the 'cpuload' script instead of having a separate process to do that.

Executing 'cmdStatus' should be ok and has to be done anyway if you want up-to-date status info.

> Or runs smartctl now completely independent and its frequency is solely determined by the new parameter 'poll-attributes' ?

Correct except for cmdSpinup and cmdSpinupAll.

> I included the creation of the directories under "smtp-init", there is no need to adjust rc.local.

Ok, but no trouble adding extra call in rc.local - I think it's better to keep those functions separate, but doesn't matter.

**Comment by eschultz** [comment]
I noticed in gfjardim's PR #82 he does a wget to emhttp if the vars are missing but also appends the correct port number (should be 80 is almost all cases unless someone has overridden it):

`wget -qO /dev/null localhost:$(lsof -nPc emhttp | grep -Po 'TCP[^\d]*\K\d+')`

**Comment by bergware** [comment]
Yeah I had included the port number as well, because I am using a different port for emhttp and obviously it didn't work initially.

**Comment by bergware** [comment]
"notify init" is also called every time a page change/refresh is done in the webGui, it didn't make sense to re-create the folders each time. It is only needed upon reboot or when the user makes a config change.

**Comment by bergware** [comment]
I have posted corrected versions, did you have a look ?
